trainer:
  seed: 2
  steps: 300000
  learning_rate: 1e-3
  final_learning_rate: ${trainer.learning_rate}
  outdir: ${oc.env:OUTDIR}
  pretrained_model: ${oc.env:MODEL_DIR}/FORMAT_best_model.pt
  expert_batch_size: 128
  snap_freq: 1024
  resume: ${oc.env:OUTDIR}/last_snap.pt
  vocab: ${oc.env:DATASET_DIR}/FORMAT_vocab.csv
  init_smiles: CC ##

  history:
    class: SimpleHistory
    backup_freq: 100
    history_dir: ${oc.env:OUTDIR}/history

  dataset:
    class: ExpertDataset2
    input_pkl: ${oc.env:DATASET_DIR}/worker

  agent:
    epochs: 2
    batch_size: 128
    update_interval: 256 #1024
    expert_coef: 0.0 #0.003 #专家损失权重
    value_func_coef: 1.0 #1.0
    entropy_coef: 0.5 #0.5  
    entropy_clip: 1.0 #策略熵超参数,熵越大,表示策略的选择越随机,熵越小,则表示策略的选择越确定.

  model:
    hidden_size: 128

  reward:
    class: SAReward
    valid_step_reward: 0.0
    invalid_step_reward: -0.1
    reuse_step_score: true
    prop_model1: ${oc.env:MODEL_DIR}/JACS_DB_PBE/fold_0/model_0/model.pt ##
    prop_model2: ${oc.env:MODEL_DIR}/JACS_DB_PBE/fold_0/model_1/model.pt
    prop_model3: ${oc.env:MODEL_DIR}/JACS_DB_PBE/fold_0/model_2/model.pt
    EPI: 1.0  #est
    ALE: 1.0
    lambda_ale: 0.0
    lambda_epi: 0.0
    k_ale: 0.5026
    k_epi: 0.3085
    eq_exp: 0.0
    eq_k: 1.0
    prop_model1_1: ${oc.env:MODEL_DIR}/S1_ehdist_0321/fold_0/model_0/model.pt ##
    prop_model2_1: ${oc.env:MODEL_DIR}/S1_ehdist_0321/fold_0/model_1/model.pt
    prop_model3_1: ${oc.env:MODEL_DIR}/S1_ehdist_0321/fold_0/model_2/model.pt
    EPI_1: 1.0  #机子尺寸
    ALE_1: 1.0
    lambda_ale_1: 0.0
    lambda_epi_1: 0.0
    k_ale_1: 3.6999
    k_epi_1: 2.6450
    eq_exp_1: 0.0
    eq_k_1: 1.0  

logger:
  level: info
